[package]
name = "mumu-url"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
futures = "0.3"
indicatif = "0.17"
reqwest = {version = "0.12", features = ["stream"] }
tokio = { version = "1.44", features = ["full"] }
